POST http://localhost:3003/user/logout
Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNTIxNTY2ZTU5ZWIyM2E2YzhmZmM5NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRGcWNselJ3Q1ZyY0U4YUhKM2pZQVZlLktwTmQycDZWMHZmSy9VdlhMczNnNk9SYkJPeVlMZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMjdUMTk6MDM6MDIuODIwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMjdUMTk6MDM6MDIuODIwWiIsIl9fdiI6MH0sImlhdCI6MTYzMjc2OTcyNX0.kzxERy9YedFj3Grv0ht89RMqFv5VVhkDCyjvlNV0FZ4`
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNTIxNTY2ZTU5ZWIyM2E2YzhmZmM5NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRGcWNselJ3Q1ZyY0U4YUhKM2pZQVZlLktwTmQycDZWMHZmSy9VdlhMczNnNk9SYkJPeVlMZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDktMjdUMTk6MDM6MDIuODIwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDktMjdUMTk6MDM6MDIuODIwWiIsIl9fdiI6MH0sImlhdCI6MTYzMjc2OTcyNX0.kzxERy9YedFj3Grv0ht89RMqFv5VVhkDCyjvlNV0FZ4"
}